name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
           sudo apt install -y libboost-program-options-dev
           sudo apt install -y llvm-12 clang-12 libclang-12-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DClang_DIR=/usr/lib/llvm-12/lib/cmake/clang -DLLVM_DIR=/usr/lib/llvm-12/lib/cmake/llvm

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Run tests
      run: ctest -C ${{env.BUILD_TYPE}}
      
    - name: Check clang-format
      run: find src include test -name '*.cpp' -o -name '*.h' | xargs clang-format -n -Werror

    - name: Check clang-tidy
      run: find src test -name '*.cpp' | xargs clang-tidy -p ${{github.workspace}}/build -header-filter=${{github.workspace}}/include --warnings-as-errors='*'
